#!/bin/bash
spotifyd \
    --no-audio-cache \
    --volume-normalisation \
    --backend 'pulseaudio' \
    --bitrate 320 \
    --device-name 'theRaggedFlagon_daemon' \
    --device-type 'computer' \
    --username '22nes3ufj37ysjc6gguxvqf7a' \
    --password 'sGVfS9n3pfQb79' \
    --initial-volume '100' \
    --volume-controller 'softvol' \
    --zeroconf-port 4444
