install:
	cp -f spt -t ~/.local/bin
	cp -f spd -t ~/.local/bin
	cp -f firefox_private -t ~/.local/bin
	cp -f start_emacsclient -t ~/.local/bin
uninstall:
	rm ~/.local/bin/spt
	rm ~/.local/bin/spd
	rm ~/.local/bin/firefox_private
	rm ~/.local/bin/start_emacsclient
