#!/bin/bash
if [[ $PWD != $HOME ]]; then
    cz_status=$(chezmoi status .)
else
    cz_status=$(chezmoi status)
fi
[[ -z $cz_status ]] && exit

parity=false
for c in $cz_status; do
    if [[ $parity != true ]]; then
        parity=true
    else
        cz_list+="~/$c\n"
        parity=false
    fi
done
file=$(echo -e $cz_list | sk --reverse)
[[ -z $file ]] && exit
chezmoi diff --reverse "$file"
cmd=''
read -r -p 'add file? [y/N] ' cmd
[[ $cmd == "y" ]] || [[ $cmd == "Y" ]] && chezmoi add "$file"
