install:
	ln -sf ~/.gurjal/links/chezmoi/cz ~/.local/bin
	ln -sf ~/.gurjal/links/chezmoi/dot_a ~/.local/bin/.a
	ln -sf ~/.gurjal/links/chezmoi/dot_ae ~/.local/bin/.ae
	ln -sf ~/.gurjal/links/chezmoi/dot_cd ~/.local/bin/.cd
	ln -sf ~/.gurjal/links/chezmoi/dot_s ~/.local/bin/.s
	ln -sf ~/.gurjal/links/chezmoi/dot_status ~/.local/bin/.status
	ln -sf ~/.gurjal/links/chezmoi/dot_ap ~/.local/bin/.apply
	ln -sf ~/.gurjal/links/chezmoi/dot_apr ~/.local/bin/.applyrefresh
	ln -sf ~/.gurjal/links/chezmoi/dot_ls ~/.local/bin/.ls
	ln -sf ~/.gurjal/links/chezmoi/dot_uls ~/.local/bin/.uls
	ln -sf ~/.gurjal/links/chezmoi/dot_d ~/.local/bin/.d
	ln -sf ~/.gurjal/links/chezmoi/dot_da ~/.local/bin/.da
uninstall:
	rm -f ~/.local/bin/cz
	rm -f ~/.local/bin/.a
	rm -f ~/.local/bin/.ae
	rm -f ~/.local/bin/.cd
	rm -f ~/.local/bin/.s
	rm -f ~/.local/bin/.status
	rm -f ~/.local/bin/.apply
	rm -f ~/.local/bin/.applyrefresh
	rm -f ~/.local/bin/.ls
	rm -f ~/.local/bin/.uls
	rm -f ~/.local/bin/.d
