install:
	ln -sf ~/.gurjal/links/chezmoi/cz ~/.local/bin
	ln -sf ~/.gurjal/links/chezmoi/dot_a ~/.local/bin/.a
	ln -sf ~/.gurjal/links/chezmoi/dot_cd ~/.local/bin/.cd
	ln -sf ~/.gurjal/links/chezmoi/dot_s ~/.local/bin/.s
	ln -sf ~/.gurjal/links/chezmoi/dot_status ~/.local/bin/.status
	ln -sf ~/.gurjal/links/chezmoi/dot_ap ~/.local/bin/.ap
	ln -sf ~/.gurjal/links/chezmoi/dot_apr ~/.local/bin/.apr
	ln -sf ~/.gurjal/links/chezmoi/dot_ls ~/.local/bin/.ls
	ln -sf ~/.gurjal/links/chezmoi/dot_uls ~/.local/bin/.uls
	ln -sf ~/.gurjal/links/chezmoi/dot_d ~/.local/bin/.d
uninstall:
	rm -f ~/.local/bin/cz
	rm -f ~/.local/bin/.a
	rm -f ~/.local/bin/.cd
	rm -f ~/.local/bin/.s
	rm -f ~/.local/bin/.status
	rm -f ~/.local/bin/.ap
	rm -f ~/.local/bin/.apr
	rm -f ~/.local/bin/.ls
	rm -f ~/.local/bin/.uls
	rm -f ~/.local/bin/.d
