install:
	ln -sf ~/.gurjal/links/system76/spower76 ~/.local/bin
	ln -sf ~/.gurjal/links/system76/sgraphics76 ~/.local/bin/
	ln -sf ~/.gurjal/links/system76/sdiscrete76 ~/.local/bin/
	ln -sf ~/.gurjal/links/system76/sprofile76 ~/.local/bin/
uninstall:
	rm -f ~/.local/bin/spower76
	rm -f ~/.local/bin/sgraphics76
	rm -f ~/.local/bin/sdiscrete76
	rm -f ~/.local/bin/sprofile76
