#!/bin/sh
userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps
[ -f $sysresources ] && xrdb -merge $sysresources
[ -f $sysmodmap ] && xmodmap $sysmodmap
[ -f "$userresources" ] && xrdb -merge "$userresources"
[ -f "$usermodmap" ] && xmodmap "$usermodmap"

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# # system76 discrete nvidia
# if system76-power graphics | grep -q 'nvidia'; then
#   xrandr --setprovideroutputsource modesetting NVIDIA-0
#   xrandr --auto
#   xrandr --dpi 96
# fi

# # syncthing start runit user service
# [ -z "$(sv status syncthing | grep run)" ] && sv up syncthing

# # emacs daemon start if not already running
# [ -z "$(ps aux | grep emacs --daemon | grep -v grep)" ] && emacs --daemon &

# redshift &
light -S 100
set-bg &
picom &
pipewire &
dunst &
xbanish &
slstatus &

# start
dbus-run-session -- dwm

# restart sig
# while :; do
#   ssh-agent dwm
# done
