#!/bin/sh
userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps
[ -f $sysresources ] && xrdb -merge $sysresources
[ -f $sysmodmap ] && xmodmap $sysmodmap
[ -f "$userresources" ] && xrdb -merge "$userresources"
[ -f "$usermodmap" ] && xmodmap "$usermodmap"

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# redshift &

# xrandr --setprovideroutputsource modesetting NVIDIA-0
# xrandr --auto

light -S 100

set_bg &

slstatus &

picom &

pipewire &

dunst &

xbanish &

emacs --daemon &

# standard start #
dbus-run-session -- dwm

# or restart sig #
# while :; do
#   ssh-agent dwm
# done
