#!/bin/bash

# thinkpad x1 gen8 firmware
xbps-install -S sof-firmware --yes

# intel microcode
xbps-install -S void-repo-nonfree --yes
xbps-install -Su --yes
xbps-install -S intel-ucode --yes

# logging
xbps-install -S socklog-void --yes

# cronjob
xbps-install -S dcron --yes

# ntp
xbps-install -S chrony --yes

# dbus elogind
xbps-install -S dbus-elogind dbus-elogind-libs dbus-elogind-x11 --yes
xbps-install -S elogind polkit --yes

# firmware updates
xbps-install -S fwupd --yes

# power saving
xbps-install -S tlp --yes

# connman
xbps-install -S connman --yes
usermod gurjal -aG network

# firewall
xbps-install -S ufw --yes

rm /etc/runit/runsvdir/default/{wpa_supplicant,dhcpcd}

# services
services=(
    dbus
    nanoklogd
    socklog-unix
    dcron
    chronyd
    tlp
    connmand
    ufw
)
for service in ${services[@]}; do
    ln -s "/etc/sv/$service" "/etc/runit/runsvdir/default"
done
xbps-reconfigure -fa
