#!/bin/bash

sudo env \
    printf "\n  running 'xbps-install -Su'...\n\n" && sudo xbps-install -Su \
    && printf "\n  running 'updatedb'...\n\n" && sudo updatedb \
    && printf "\n  running 'xlocate -S'...\n\n" && xlocate -S \
    && printf "\n  running 'tldr --update'...\n\n" && tldr --update \
    && printf "\n  done.\n\n> go update void-packages\n"
    # && printf "\n  running 'nix-channel --update'...\n\n" && nix-channel --update \
    # && printf "\n  running 'nix-env -u'...\n\n" && nix-env -u
