install:
	ln -sf ~/.gurjal/links/distro/void/x ~/.local/bin
	ln -sf ~/.gurjal/links/distro/void/xs ~/.local/bin
	ln -sf ~/.gurjal/links/distro/void/xy ~/.local/bin
	ln -sf ~/.gurjal/links/distro/void/xr ~/.local/bin
	ln -sf ~/.gurjal/links/distro/void/xilogm ~/.local/bin
	ln -sf ~/.gurjal/links/distro/void/xu ~/.local/bin
	ln -sf ~/.gurjal/links/distro/void/poweroff ~/.local/bin
	ln -sf ~/.gurjal/links/distro/void/reboot ~/.local/bin
uninstall:
	rm ~/.local/bin/x
	rm ~/.local/bin/xs
	rm ~/.local/bin/xy
	rm ~/.local/bin/xr
	rm ~/.local/bin/xilogm
	rm ~/.local/bin/xu
	rm ~/.local/bin/poweroff
	rm ~/.local/bin/reboot
