install:
	ln -sf ~/.gurjal/links/distro/void/xs ~/.local/bin
	ln -sf ~/.gurjal/links/distro/void/xr ~/.local/bin
	ln -sf ~/.gurjal/links/distro/void/xilogm ~/.local/bin
	ln -sf ~/.gurjal/links/distro/void/xu ~/.local/bin
	ln -sf ~/.gurjal/links/distro/void/poweroff ~/.local/bin
	ln -sf ~/.gurjal/links/distro/void/reboot ~/.local/bin
uninstall:
	rm -f ~/.local/bin/xs
	rm -f ~/.local/bin/xr
	rm -f ~/.local/bin/xilogm
	rm -f ~/.local/bin/xu
	rm -f ~/.local/bin/poweroff
	rm -f ~/.local/bin/reboot
