#!/bin/bash

[ ! -z "$(rbw unlocked 2>&1)" ] && rbw unlock
name=$(rbw ls | sk)
[ -z $name ] && exit
cmd=''
read -r -p 'copy username? [Y/n] ' cmd
if [[ $cmd != 'n' ]] && [[ $cmd != 'N' ]]; then
    rbw get $name --full | head -2 | tail -1 | cut -d' ' -f2- \
        | xclip -sel clip
fi
cmd=''
read -r -p 'copy password? [Y/n] ' cmd
if [[ $cmd != 'n' ]] && [[ $cmd != 'N' ]]; then
    rbw get $name | xclip -sel clip
fi
