#!/bin/bash

export _CONFIG_PATH="/home/gurjal/.gurjal/notes/configs"
export _HOSTNAME='theRaggedFlagon'
export _REPO=https://repo-default.voidlinux.org/current/musl
export _ARCH=x86_64-musl

# exit when any command fails
set -e
# keep track of the last executed command
trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG
# echo an error message before exiting
trap 'echo "\"${last_command}\" command filed with exit code $?."' EXIT
