#!/bin/bash

cd
mkdir Source

# gui setup
cd Source
git clone https://github.com/gurjal/gui -b main
cd gui

# dmenu
git clone https://github.com/gurjal/dmenu -b main
cd dmenu && sudo make clean install && cd ..

# dwm
git clone https://github.com/gurjal/dwm -b main
cd dwm && sudo make clean install && cd ..

# slstatus
git clone https://github.com/gurjal/slstatus -b main
cd slstatus && sudo make clean install && cd ..

# st
git clone https://github.com/gurjal/st -b main
cd st && sudo make clean install && cd ..

# tabbed
git clone https://github.com/gurjal/tabbed -b main
cd tabbed && sudo make clean install && cd ..

# gtk
sudo xbps-install -S lxappearance arandr --yes

# gtk theme
[[ ! -d "/usr/share/themes" ]] && mkdir -p "/usr/share/themes"
cd "$HOME"
git clone "https://github.com/EliverLara/Nordic.git" -b darker
sudo mv "Nordic" "/usr/share/themes/"

# gtk cursor
[[ ! -d "/usr/share/icons" ]] && mkdir -p "/usr/share/icons"
cd "$HOME"
git clone "https://github.com/alvatip/Nordzy-cursors.git"
sudo mv "Nordzy-cursors/Nordzy-cursors" "/usr/share/icons/"
sudo mv "Nordzy-cursors/Nordzy-cursors-white" "/usr/share/icons/"
rm -rf "Nordzy-cursors"

# wallpapers
xdg-user-dirs-update
cd "$HOME/Pictures/"
git clone "https://github.com/gurjal/wallpapers.git"
