#!/bin/bash

# trashman cli
#

[ -z $_TRASH_DIR ] && _TRASH_DIR=$HOME/.cache/trashcan

[ ! -d $_TRASH_DIR ] && mkdir -p $_TRASH_DIR

help()
{
  echo "usage: trashman [TRASH]..."
  echo "move items to the trashcan"
  echo
  echo "  -l, --list      list items in trashcan"
  echo "  -r, --restore   search items in trashcan and restore"
  echo "  -c, --clear     clear trashcan"
  echo "  -s, --status    print trashcan status"
  echo "  -h, --help      uuhhh"
}

trash_list()
{
  ls -A1 "$_TRASH_DIR"
}

trash_restore()
{
  item=$(
    ls -A $_TRASH_DIR | fzf --layout=reverse --height=90% \
      --bind=alt-j:preview-half-page-down,alt-k:preview-half-page-up
  )
  [[ -z "$item" ]] && return
  mv -f "$_TRASH_DIR/$item" $(pwd)
}

trash_clear()
{
  echo "clearing trashcan..."
  echo
  echo "  count -> $(ls -A $_TRASH_DIR | wc -l)"
  echo "  space -> $(du -sh $_TRASH_DIR | awk '{print $1}')"
  echo
  read -p "you sure boss? [Y/n] " _cmd
  if [[ "${#_cmd}" -eq 0 || "$_cmd" == "y" || "$_cmd" == "Y" ]]; then
    echo "  you got it"
    for f in $(ls -A $_TRASH_DIR); do
      rm -rf "$_TRASH_DIR"/"$f"
    done
    echo "  all clear"
  elif [[ "$_cmd" == "n" || "$_cmd" == "N" ]]; then
    echo "  got it we're bailing out"
  else
    echo "  what?"
  fi
}

trash_status()
{
  echo "trashcan status"
  echo
  echo "  count -> $(ls -A $_TRASH_DIR | wc -l)"
  echo "  space -> $(du -sh $_TRASH_DIR | awk '{print $1}')"
  echo "  path  -> $_TRASH_DIR"
  echo
}

if [ -z "$1" ]; then
  trash_list
else
  while [ -n "$1" ]; do
    case "$1" in
      -l | --list)
        trash_list
        exit
        ;;
      -r | --restore)
        trash_restore
        exit
        ;;
      -c | --clear)
        trash_clear
        exit
        ;;
      -s | --status)
        trash_status
        exit
        ;;
      -h | --help)
        help
        exit
        ;;
      *)
        mv -f "$1" "$_TRASH_DIR"
        ;;
    esac
    shift
  done
fi
