install:
	sudo cp ~/.gurjal/apps/display_cam /usr/local/bin
	sudo cp ~/.gurjal/apps/dj /usr/local/bin
	sudo cp ~/.gurjal/apps/trashman /usr/local/bin
	sudo cp ~/.gurjal/apps/sxiv_rifle /usr/local/bin
	sudo cp ~/.gurjal/apps/set_bg /usr/local/bin
	sudo cp ~/.gurjal/apps/take_screen /usr/local/bin
	sudo cp ~/.gurjal/apps/scribe /usr/local/bin
uninstall:
	sudo rm -f /usr/local/bin/display_cam
	sudo rm -f /usr/local/bin/dj
	sudo rm -f /usr/local/bin/trashman
	sudo rm -f /usr/local/bin/sxiv_rifle
	sudo rm -f /usr/local/bin/set_bg
	sudo rm -f /usr/local/bin/take_screen
	sudo rm -f /usr/local/bin/scribe
