install:
	ln -sf ~/.gurjal/apps/display_cam ~/.local/bin
	ln -sf ~/.gurjal/apps/dj ~/.local/bin
	ln -sf ~/.gurjal/apps/trashman ~/.local/bin
	ln -sf ~/.gurjal/apps/nsxiv_rifle ~/.local/bin
	ln -sf ~/.gurjal/apps/set_bg ~/.local/bin
	ln -sf ~/.gurjal/apps/take_screen ~/.local/bin
	ln -sf ~/.gurjal/apps/scribe ~/.local/bin
uninstall:
	rm -f ~/.local/bin/display_cam
	rm -f ~/.local/bin/dj
	rm -f ~/.local/bin/trashman
	rm -f ~/.local/bin/nsxiv_rifle
	rm -f ~/.local/bin/set_bg
	rm -f ~/.local/bin/take_screen
	rm -f ~/.local/bin/scribe
