cleaninstall:
	make uninstall install
install:
	cp display_cam -t ~/.local/bin
	cp dj -t ~/.local/bin
	cp trashman -t ~/.local/bin
	cp nsxiv_rifle -t ~/.local/bin
	cp set_bg -t ~/.local/bin
	cp take_screen -t ~/.local/bin
	cp scribe -t ~/.local/bin
uninstall:
	rm -f ~/.local/bin/display_cam
	rm -f ~/.local/bin/dj
	rm -f ~/.local/bin/trashman
	rm -f ~/.local/bin/nsxiv_rifle
	rm -f ~/.local/bin/set_bg
	rm -f ~/.local/bin/take_screen
	rm -f ~/.local/bin/scribe
