#!/bin/zsh

# completion
# fpath=($ZSH_BIN $fpath)
autoload -Uz compinit
compinit -d "$XDG_CACHE_HOME/zsh_compdump"
_comp_options+=(globdots);

# history
HISTFILE="$XDG_CACHE_HOME/zsh_hist"
HISTSIZE=1000
SAVEHIST=1000
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt inc_append_history

# type only directory name to cd
setopt auto_cd

# turn off case sensitivity
setopt no_case_glob

# expand prompt substring
setopt PROMPT_SUBST
