clone:
	git clone https://github.com/zsh-users/zsh-syntax-highlighting.git
	git clone https://github.com/zsh-users/zsh-history-substring-search.git
	git clone https://github.com/jeffreytse/zsh-vi-mode.git
